Document: musicus
Title: Debian musicus Manual
Author: <insert document author here>
Abstract: This manual describes what musicus is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/musicus/musicus.sgml.gz

Format: postscript
Files: /usr/share/doc/musicus/musicus.ps.gz

Format: text
Files: /usr/share/doc/musicus/musicus.text.gz

Format: HTML
Index: /usr/share/doc/musicus/html/index.html
Files: /usr/share/doc/musicus/html/*.html


